name: DrJosephRiggio
favicon: null
layout_spectrum: 0.95094
typography_spectrum: 0.6942754026968032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#40210d'
    - '#f69232'
    - '#c07126'
    - '#874d1b'
    - '#623613'
  brandStrength: 1
  lightness: 0.42188271251507103
  saturation: 0.25414156331680715
  rhythmicContrast: 0.26065746136009693
purpose: []
